version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - patrykjadamczyk
  assignees:
  - patrykjadamczyk
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.33
    - 14.14.34
